import test from 'ava';
import m from './';

test(t => {
	t.is(m('foo'), 'Foo');
	t.is(m('foo-bar'), 'FooBar');
	t.is(m('foo-bar-baz'), 'FooBarBaz');
	t.is(m('foo--bar'), 'FooBar');
	t.is(m('--foo-bar'), 'FooBar');
	t.is(m('--foo--bar'), 'FooBar');
	t.is(m('FOO-BAR'), 'FooBar');
	t.is(m('-foo-bar-'), 'FooBar');
	t.is(m('--foo--bar--'), 'FooBar');
	t.is(m('foo.bar'), 'FooBar');
	t.is(m('foo..bar'), 'FooBar');
	t.is(m('..foo..bar..'), 'FooBar');
	t.is(m('foo_bar'), 'FooBar');
	t.is(m('__foo__bar__'), 'FooBar');
	t.is(m('__foo__bar__'), 'FooBar');
	t.is(m('foo bar'), 'FooBar');
	t.is(m('  foo  bar  '), 'FooBar');
	t.is(m('-'), '-');
	t.is(m(' - '), '-');
	t.is(m('fooBar'), 'FooBar');
	t.is(m('fooBar-baz'), 'FoobarBaz');
	t.is(m('F'), 'F');
	t.is(m('Foo'), 'Foo');
	t.is(m('FOO'), 'Foo');
	t.is(m('foo', 'bar'), 'FooBar');
	t.is(m('foo', '-bar'), 'FooBar');
	t.is(m('foo', '-bar', 'baz'), 'FooBarBaz');
	t.is(m('', ''), '');
	t.is(m('--'), '');
	t.is(m(''), '');
	t.is(m('--__--_--_'), '');
	t.is(m('---_', '--', '', '-_- '), '');
});
