import test from 'ava';
import fn from './';

test('UpperCamelCase', t => {
	t.is(fn('foo'), 'Foo');
	t.is(fn('foo-bar'), 'FooBar');
	t.is(fn('foo-bar-baz'), 'FooBarBaz');
	t.is(fn('foo--bar'), 'FooBar');
	t.is(fn('--foo-bar'), 'FooBar');
	t.is(fn('--foo--bar'), 'FooBar');
	t.is(fn('FOO-BAR'), 'FooBar');
	t.is(fn('-foo-bar-'), 'FooBar');
	t.is(fn('--foo--bar--'), 'FooBar');
	t.is(fn('foo.bar'), 'FooBar');
	t.is(fn('foo..bar'), 'FooBar');
	t.is(fn('..foo..bar..'), 'FooBar');
	t.is(fn('foo_bar'), 'FooBar');
	t.is(fn('__foo__bar__'), 'FooBar');
	t.is(fn('__foo__bar__'), 'FooBar');
	t.is(fn('foo bar'), 'FooBar');
	t.is(fn('  foo  bar  '), 'FooBar');
	t.is(fn('-'), '-');
	t.is(fn(' - '), '-');
	t.is(fn('fooBar'), 'FooBar');
	t.is(fn('fooBar-baz'), 'FoobarBaz');
	t.is(fn('F'), 'F');
	t.is(fn('Foo'), 'Foo');
	t.is(fn('FOO'), 'Foo');
	t.is(fn('foo', 'bar'), 'FooBar');
	t.is(fn('foo', '-bar'), 'FooBar');
	t.is(fn('foo', '-bar', 'baz'), 'FooBarBaz');
	t.is(fn('', ''), '');
	t.is(fn('--'), '');
	t.is(fn(''), '');
	t.is(fn('--__--_--_'), '');
	t.is(fn('---_', '--', '', '-_- '), '');
	t.end();
});
